test:
  image: python:3.8
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: ci
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  cache:
    paths:
      - ~/.cache/pip/
  script:
    - pip install -r requirements.prod.txt
    - pip install psycopg2-binary
    - cp ci_settings.py local_settings.py
    - python manage.py test
