# Generated by Django 3.0.1 on 2020-04-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productproperty_propertyoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='is_main_property',
            field=models.BooleanField(default=False, verbose_name='Main property'),
        ),
    ]
