# Generated by Django 3.0.1 on 2020-04-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200427_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='value_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='value_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='propertyoption',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Property name'),
        ),
        migrations.AddField(
            model_name='propertyoption',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Property name'),
        ),
    ]
