# Generated by Django 3.0.1 on 2020-04-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200427_0352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('rank',), 'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='rank',
            field=models.IntegerField(default=1, verbose_name='Order rank'),
        ),
    ]
