# Generated by Django 3.0.1 on 2020-05-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60, verbose_name='name')),
                ('surname', models.CharField(default='', max_length=60, verbose_name='surname')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=60, unique=True, verbose_name='phone')),
                ('city', models.CharField(default='', max_length=60, verbose_name='city')),
                ('district', models.CharField(default='', max_length=60, verbose_name='district')),
                ('neighborhood', models.CharField(default='', max_length=60, verbose_name='neighborhood')),
                ('others', models.CharField(default='', max_length=100, verbose_name='others')),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
            },
        ),
    ]
