# Generated by Django 3.0.1 on 2020-05-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': 'shipment', 'verbose_name_plural': 'shipments'},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='deneme',
        ),
    ]
