# Generated by Django 3.0.1 on 2020-05-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinformation',
            name='address_name_b',
            field=models.CharField(default='', max_length=60, verbose_name='address_name_b'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='address_name',
            field=models.CharField(default='', max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='billinformation',
            name='email_b',
            field=models.EmailField(max_length=60, verbose_name='email_b'),
        ),
        migrations.AlterField(
            model_name='billinformation',
            name='phone_b',
            field=models.CharField(max_length=60, verbose_name='phone_b'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='address_name'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='phone',
            field=models.CharField(max_length=60, verbose_name='phone'),
        ),
    ]
