# Generated by Django 3.0.1 on 2020-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20200517_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='selection',
            field=models.IntegerField(default=0, verbose_name='selection_number'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='address_name',
            field=models.CharField(default='', max_length=60, verbose_name='address_name'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='BillInformation',
        ),
    ]
