# Generated by Django 3.0.1 on 2020-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20200505_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='city',
            field=models.CharField(default='', max_length=60, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='district',
            field=models.CharField(default='', max_length=60, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='neighborhood',
            field=models.CharField(default='', max_length=60, verbose_name='neighborhood'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='others',
            field=models.CharField(default='', max_length=100, verbose_name='others'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='surname',
            field=models.CharField(default='', max_length=60, verbose_name='surname'),
        ),
    ]
