# Generated by Django 3.0.1 on 2020-05-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_auto_20200517_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='id',
        ),
        migrations.AddField(
            model_name='shipment',
            name='address_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='extra',
            field=models.CharField(default='', max_length=100, verbose_name='extra'),
        ),
    ]
