# Generated by Django 3.0.1 on 2020-05-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_auto_20200517_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='address_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='address_id'),
        ),
    ]
